### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by pkerpedjiev** [Rostlab/SeqVec#11]
Hey, thanks for making this package available! I'm excited to try it out but am getting this error when trying to install using pip:

```
(cenv4) pkerpedjiev$ pip install seqvec
Collecting seqvec
  Downloading seqvec-0.2.0-py3-none-any.whl (10 kB)
ERROR: Could not find a version that satisfies the requirement torch<1.3,>=1.2 (from seqvec) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.4.0)
ERROR: No matching distribution found for torch<1.3,>=1.2 (from seqvec)
```

Any suggestions?

**Comment by mheinzinger** [comment]
Hey,

I tried to reproduce your error with a new conda-environment using Python 3.7.6, GCC 7.3.0, CUDA 10.2 (Driver Version: 440.64) but the installation worked without problems. For me, pytorch 1.2 was installed automatically. Maybe you need to install this specific pytorch version manually [something like: pip install torch==1.2.0], before installing seqvec.

Best,
Michael

**Comment by konstin** [comment]
Could you please paste the output of `pip debug --verbose`?

**Comment by pkerpedjiev** [comment]
Thanks for the quick response!

Here's the output of `pip debug --verbose`:

[out.txt](https://github.com/Rostlab/SeqVec/files/4462212/out.txt)

Maybe it's because I'm using Python 3.8? I got it to run by creating a fresh conda environment with Python 3.7.

**Comment by mheinzinger** [comment]
The version conflict should be resolved with the latest updates. I'll also add a short note on this to the readme.
