### ISSUE TITLE
ELMo-Tutorial website 404

### ISSUE THREAD

**Issue by zi-xiao** [Rostlab/SeqVec#17]
It returns 404 not found error, while opening the link of ELMo-Tutorial.

**Comment by mheinzinger** [comment]
Thanks for notifying. This is a known problem in the original allennlp ELMo repository: https://github.com/allenai/allennlp/issues/1737
For the moment being, I simply re-direct to the original tf implementation of ELMo: https://github.com/allenai/bilm-tf
